name: Publish npm package

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
    workflow_call:
        inputs:
            name:
                required: true
                type: string
                description: 'Name of the package directory to publish'
            packageName:
                required: true
                type: string
                description: 'Name of the package to publish'
        secrets:
            NPM_TOKEN:
                required: true

jobs:
    publish:
        name: Publish ${{ inputs.name }}
        runs-on: ubuntu-latest

        steps:
        # Ensuring that only one PR-environment-creation per branch will run at a time
        - name: Mutex setup
          uses: ben-z/gh-action-mutex@v1.0-alpha-7
          with:
            branch: "mutex/${{ github.event.workflow_run.head_branch }}-publish"

        # Default the GK_TOKEN to GITHUB_TOKEN if not present
        - name: Look for GH_TOKEN
          if: env.GH_TOKEN == ''
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: echo "GH_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

        - uses: actions/checkout@v4
          with:
            ref: main
            token: ${{ env.GH_TOKEN }}

        - name: Setup pnpm
          uses: pnpm/action-setup@v3.0.0
          with:
            version: 'latest'

        - uses: actions/setup-node@v4
          with:
            node-version: "22.16.0"
            cache: "pnpm"

        - name: Setup npmrc
          run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          env:
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

        - name: Changelog
          id: version-bump
          uses: Enterwell/ChangelogManager-GitHub-Action@v3
          with:
            changelog-location: ./packages/${{ inputs.name }}
            should-bump-version: true
            changes-location: ./packages/${{ inputs.name }}/changes
            path-to-project-file: ./packages/${{ inputs.name }}/package.json

        - name: Commit changelog changes
          uses: EndBug/add-and-commit@v9.1.4
          with:
            message: "[skip ci] [version-bump] Automated commit for version ${{ steps.version-bump.outputs.bumped-semantic-version }}"

        - run: pnpm i --frozen-lockfile --filter=${{ inputs.packageName }}...
        - run: pnpm build --filter=${{ inputs.packageName }}...
        - run: pnpm publish --access public --filter=${{ inputs.packageName }} --no-git-checks

        - name: Git tags update
          run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
  
            git tag "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
            git tag -f "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-major-part }}" "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
            git tag -f "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-major-part }}.${{ steps.version-bump.outputs.bumped-minor-part }}" "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}"
  
            git push -f --tags

        - name: Create GitHub release
          run: gh release create "${{ inputs.name }}/v${{ steps.version-bump.outputs.bumped-semantic-version }}" -n "${{ steps.version-bump.outputs.new-changes }}"
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
